config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/dashboard' => 'dashboard#show'

  get 'auth/auth0/logout' => 'auth0#logout'

  get 'auth/auth0', as: 'authentication'        # Triggers authentication process
  get 'auth/auth0/callback' => 'auth0#callback' # Authentication successful
  get 'auth/failure' => 'auth0#failure'         # Authentication fail
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/auth0_controller.rb
# ./app/controllers/auth0_controller.rb
class Auth0Controller < ApplicationController
  def callback
    # OmniAuth stores the informatin returned from Auth0 and the IdP in request.env['omniauth.auth'].
    # In this code, you will pull the raw_info supplied from the id_token and assign it to the session.
    # Refer to https://github.com/auth0/omniauth-auth0#authentication-hash for complete information on 'omniauth.auth' contents.
    auth_info = request.env['omniauth.auth']
    session[:userinfo] = auth_info['extra']['raw_info']

    # Redirect to the URL you want after successful auth
    redirect_to '/dashboard'
  end

  def failure
    # Handles failed authentication -- Show a failure page (you can also handle with a redirect)
    @error_msg = request.params['message']
  end

  def logout
    reset_session
    redirect_to logout_url
  end

  private
  AUTH0_CONFIG = Rails.application.config_for(:auth0)

  def logout_url
    request_params = {
      returnTo: root_url,
      client_id: AUTH0_CONFIG['auth0_client_id']
    }

    URI::HTTPS.build(host: AUTH0_CONFIG['auth0_domain'], path: '/v2/logout', query: to_query(request_params)).to_s
  end

  def to_query(hash)
    hash.map { |k, v| "#{k}=#{CGI.escape(v)}" unless v.nil? }.reject(&:nil?).join('&')
  end
end

app/controllers/concerns/secured.rb
# ./app/controllers/concerns/secured.rb
module Secured
  extend ActiveSupport::Concern

  included do
    before_action :logged_in_using_omniauth?
  end

  def logged_in_using_omniauth?
    redirect_to '/' unless session[:userinfo].present?
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  include Secured

  def show
    # session[:userinfo] was saved earlier on Auth0Controller#callback
    @user = session[:userinfo]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/dashboard/show.html.erb
<section class="jumbotron  text-center">
   <h2><img class="jumbo-thumbnail" src="<%= @user['picture'] %>"/></h2>
  <h1>Welcome, <%= @user['nickname'] %></h1>
  <h2><img class="jumbo-thumbnail" src="https://flagpedia.net/data/flags/w580/<%= @user['https://example.com/country'].to_str().downcase() =%>.png"/></h2>
  <%= button_to 'Logout', 'auth/auth0/logout', method: :get %>

</section>

app/views/home/dashboard.html.erb
<h1>Home#dashboard</h1>
<p>Find me in app/views/home/dashboard.html.erb</p>
  <%= button_to 'Logout', 'auth/auth0/logout', method: :get %>
<div>
  <p>Normalized User Profile:<%= JSON.pretty_generate(@user)%></p>
</div>

app/views/home/index.html.erb
<div class="jumbotron">
  <center>
    <h1>Cruise0</h1>

    <%= link_to 'Login', authentication_path, class: "btn btn-primary btn-lg" %>
  </center>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cruise0</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>